module.exports.descriptors = [
  "Forest",
  "Ancient",
  "Petrified",
  "Roaring",
  "Cascade",
  "Tumbling",
  "Silent",
  "Redwood",
  "Bullfrog",
  "Maple",
  "Misty",
  "Elk",
  "Grizzly",
  "Ocean",
  "Sea",
  "Sky",
  "Dusty",
  "Diamond",
];

module.exports.places = [
  "Flats",
  "Village",
  "Canyon",
  "Pond",
  "Group Camp",
  "Horse Camp",
  "Ghost Town",
  "Camp",
  "Dispersed Camp",
  "Backcountry",
  "River",
  "Creek",
  "Creekside",
  "Bay",
  "Spring",
  "Bayshore",
  "Sands",
  "Mule Camp",
  "Hunting Camp",
  "Cliffs",
  "Hollow",
];

module.exports.description_base = [
  "A peaceful retreat surrounded by the natural beauty of the outdoors. Perfect for relaxing and reconnecting with nature.",
  "Spacious campsites with plenty of room to set up and enjoy the fresh air. Ideal for both solo travelers and families.",
  "Enjoy quiet evenings under the stars with this simple and serene camping experience.",
  "A clean, well-maintained campground offering a comfortable space to pitch your tent and unwind.",
  "An excellent spot for weekend getaways, complete with everything you need for a memorable trip.",
  "This campsite offers a calm and cozy atmosphere, making it great for unplugging from daily life.",
  "Easy access, great amenities, and a relaxing vibe — this campground is perfect for any kind of camper.",
  "A welcoming place to stay whether you're road-tripping, hiking, or just looking for a night in nature.",
  "Take a break from the noise and enjoy peaceful days and quiet nights in this charming campground.",
  "A simple and accessible camping spot with all the basics covered for a smooth and enjoyable stay.",
  "Whether you're new to camping or a seasoned explorer, this site provides a balanced and relaxing experience.",
  "A friendly campground that balances convenience with the tranquility of outdoor life.",
  "This site provides a comfortable blend of nature and functionality, perfect for a short or long stay.",
  "Clean surroundings, fresh air, and a calm environment make this spot a great camping destination.",
  "Escape the ordinary and relax in a quiet, uncrowded campground with everything you need.",
  "An ideal location for campers looking for simplicity, comfort, and a peaceful setting.",
  "This campground is known for its quiet ambiance and ease of access — suitable for all ages.",
  "A hassle-free camping experience with well-spaced sites and a welcoming atmosphere.",
  "Great for first-time campers or regular adventurers — this spot makes outdoor living easy.",
  "Everything you need for a calm and carefree camping experience, in one neatly arranged space.",
];
